<a href="https://colab.research.google.com/github/rajeevfromkrec/deep_learning/blob/master/bert_simple_model_and_output_explained.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install transformers

     |████████████████████████████████| 665kB 2.7MB/s 
     |████████████████████████████████| 1.1MB 15.0MB/s 
     |████████████████████████████████| 890kB 16.4MB/s 
     |████████████████████████████████| 3.8MB 26.2MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=321d4471b9833219fe0c44db94714cdd427667a0e38ecd973684c65d2a50f48a
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [0]:
s= " this is a lage corpus .."
words=s.split()
vocab= dict(enumerate(words))

In [3]:
vocab

{0: 'this', 1: 'is', 2: 'a', 3: 'lage', 4: 'corpus', 5: '..'}

In [0]:
from transformers import BertTokenizer
model_name="bert-base-cased"

In [6]:
bert_token= BertTokenizer.from_pretrained(model_name)

In [0]:
sen="Hi this is rajeev"
enc=bert_token.encode(sen)

In [9]:
print(enc)
print(bert_token.decode(enc))

[101, 8790, 1142, 1110, 187, 12487, 3051, 1964, 102]
[CLS] Hi this is rajeev [SEP]


In [0]:
import tensorflow as tf

In [0]:
from transformers import DistilBertTokenizer,TFDistilBertModel

In [0]:
model_name='distilbert-base-uncased'

In [13]:
tokenizer=DistilBertTokenizer.from_pretrained(model_name)
model=TFDistilBertModel.from_pretrained(model_name)

In [0]:
e=tokenizer.encode("today's movie was realy great.i liked it")

In [0]:
input=tf.constant(e)[None,:]

In [0]:
output=model(input)

In [17]:
print(output)

(<tf.Tensor: shape=(1, 14, 768), dtype=float32, numpy=
array([[[ 0.15157515, -0.26314595,  0.10739828, ..., -0.12770289,
          0.406785  ,  0.2143284 ],
        [-0.35142002, -0.1950108 , -0.2246106 , ..., -0.27551782,
          0.6033122 , -0.7363107 ],
        [ 0.05507795, -0.56311256,  0.3821179 , ..., -0.2372811 ,
          0.528416  , -0.52765536],
        ...,
        [ 0.20976768, -0.0540644 ,  0.4779727 , ..., -0.03327958,
          0.37144735,  0.1602858 ],
        [-0.04507186, -0.666519  , -0.01955395, ...,  0.09407885,
          0.2720136 , -0.20018616],
        [ 0.80260384,  0.1748421 ,  0.01704261, ...,  0.11530201,
         -0.28183675, -0.45213506]]], dtype=float32)>,)


In [18]:
output[0][0,0,:]  #output for CLS

<tf.Tensor: shape=(768,), dtype=float32, numpy=
array([ 1.51575148e-01, -2.63145953e-01,  1.07398279e-01,  4.01002504e-02,
       -6.93500936e-02, -2.72732496e-01,  7.27978274e-02,  5.40895164e-01,
        3.13128456e-02, -1.41176283e-01,  9.25550014e-02, -4.17054966e-02,
        8.75447392e-02,  4.47073638e-01,  1.33691922e-01,  1.70864686e-01,
        1.21657923e-02,  7.30126873e-02,  1.30808756e-01, -8.67791772e-02,
       -1.41436845e-01, -3.19925845e-01,  2.44796146e-02,  2.32029438e-01,
       -1.56416014e-01,  1.55275743e-02, -4.35667224e-02, -7.05435276e-02,
        2.36837462e-01,  1.39635727e-01,  9.87878293e-02,  4.62015942e-02,
       -4.32938755e-01, -1.76425219e-01, -2.91702598e-02, -2.00533405e-01,
       -8.38612765e-02, -2.66956627e-01, -1.16008654e-01, -7.13301729e-03,
       -1.78144500e-02, -1.42641328e-02,  1.59184366e-01, -6.42663836e-02,
       -2.67069668e-01, -1.51331544e-01, -2.58518624e+00,  6.50170520e-02,
       -1.24601044e-01, -3.02384973e-01,  4.79172707

In [0]:
from transformers import DistilBertConfig

In [0]:
config=DistilBertConfig.from_pretrained(model_name,output_hidden_states= True)

In [0]:
model=TFDistilBertModel.from_pretrained(model_name,config=config)

In [0]:
output=model(input)

In [23]:
type(output)

tuple

In [25]:
print(output[0])

tf.Tensor(
[[[ 0.15157515 -0.26314595  0.10739828 ... -0.12770289  0.406785
    0.2143284 ]
  [-0.35142002 -0.1950108  -0.2246106  ... -0.27551782  0.6033122
   -0.7363107 ]
  [ 0.05507795 -0.56311256  0.3821179  ... -0.2372811   0.528416
   -0.52765536]
  ...
  [ 0.20976768 -0.0540644   0.4779727  ... -0.03327958  0.37144735
    0.1602858 ]
  [-0.04507186 -0.666519   -0.01955395 ...  0.09407885  0.2720136
   -0.20018616]
  [ 0.80260384  0.1748421   0.01704261 ...  0.11530201 -0.28183675
   -0.45213506]]], shape=(1, 14, 768), dtype=float32)


In [26]:
print(output[1])

(<tf.Tensor: shape=(1, 14, 768), dtype=float32, numpy=
array([[[ 3.4693521e-01, -1.6263762e-01, -2.3334563e-01, ...,
          1.4869013e-01,  8.6534560e-02,  1.4215374e-01],
        [-1.0047455e+00, -9.9143147e-02, -1.1042811e+00, ...,
          4.0266180e-01,  6.9931960e-01, -4.8665494e-01],
        [-7.7775431e-01, -7.1177185e-02,  2.4312153e-01, ...,
          6.4759958e-01,  6.3680232e-01, -1.7200712e+00],
        ...,
        [-9.3307519e-01,  4.2615801e-01,  6.3079882e-01, ...,
         -2.5537837e-01, -2.9449266e-01,  2.3637059e-01],
        [-8.1787771e-01, -4.9718815e-01,  2.9226348e-01, ...,
          6.1402828e-01,  1.9668402e-01,  4.1631299e-01],
        [-5.9785068e-01, -9.9929273e-03, -8.9519128e-02, ...,
         -2.1215832e-01,  2.1721298e-01,  1.3380013e-03]]], dtype=float32)>, <tf.Tensor: shape=(1, 14, 768), dtype=float32, numpy=
array([[[-0.04211216,  0.05827064, -0.0523908 , ...,  0.27756923,
          0.02239491,  0.00694019],
        [-0.55709624,  0.25584   , -0